// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: plugin-pb/discovery/v1/discovery.proto

package discovery

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersions) Reset() {
	*x = GetVersions{}
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersions) ProtoMessage() {}

func (x *GetVersions) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersions.ProtoReflect.Descriptor instead.
func (*GetVersions) Descriptor() ([]byte, []int) {
	return file_plugin_pb_discovery_v1_discovery_proto_rawDescGZIP(), []int{0}
}

type GetVersions_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersions_Request) Reset() {
	*x = GetVersions_Request{}
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersions_Request) ProtoMessage() {}

func (x *GetVersions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersions_Request.ProtoReflect.Descriptor instead.
func (*GetVersions_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_discovery_v1_discovery_proto_rawDescGZIP(), []int{0, 0}
}

type GetVersions_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []int32                `protobuf:"varint,1,rep,packed,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersions_Response) Reset() {
	*x = GetVersions_Response{}
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersions_Response) ProtoMessage() {}

func (x *GetVersions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_discovery_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersions_Response.ProtoReflect.Descriptor instead.
func (*GetVersions_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_discovery_v1_discovery_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetVersions_Response) GetVersions() []int32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_plugin_pb_discovery_v1_discovery_proto protoreflect.FileDescriptor

const file_plugin_pb_discovery_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"&plugin-pb/discovery/v1/discovery.proto\x12\x17cloudquery.discovery.v1\"@\n" +
	"\vGetVersions\x1a\t\n" +
	"\aRequest\x1a&\n" +
	"\bResponse\x12\x1a\n" +
	"\bversions\x18\x01 \x03(\x05R\bversions2w\n" +
	"\tDiscovery\x12j\n" +
	"\vGetVersions\x12,.cloudquery.discovery.v1.GetVersions.Request\x1a-.cloudquery.discovery.v1.GetVersions.ResponseB\\\n" +
	"\x1aio.cloudquery.discovery.v1P\x01Z<github.com/cloudquery/plugin-pb-go/pb/discovery/v1;discoveryb\x06proto3"

var (
	file_plugin_pb_discovery_v1_discovery_proto_rawDescOnce sync.Once
	file_plugin_pb_discovery_v1_discovery_proto_rawDescData []byte
)

func file_plugin_pb_discovery_v1_discovery_proto_rawDescGZIP() []byte {
	file_plugin_pb_discovery_v1_discovery_proto_rawDescOnce.Do(func() {
		file_plugin_pb_discovery_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_discovery_v1_discovery_proto_rawDesc), len(file_plugin_pb_discovery_v1_discovery_proto_rawDesc)))
	})
	return file_plugin_pb_discovery_v1_discovery_proto_rawDescData
}

var file_plugin_pb_discovery_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_plugin_pb_discovery_v1_discovery_proto_goTypes = []any{
	(*GetVersions)(nil),          // 0: cloudquery.discovery.v1.GetVersions
	(*GetVersions_Request)(nil),  // 1: cloudquery.discovery.v1.GetVersions.Request
	(*GetVersions_Response)(nil), // 2: cloudquery.discovery.v1.GetVersions.Response
}
var file_plugin_pb_discovery_v1_discovery_proto_depIdxs = []int32{
	1, // 0: cloudquery.discovery.v1.Discovery.GetVersions:input_type -> cloudquery.discovery.v1.GetVersions.Request
	2, // 1: cloudquery.discovery.v1.Discovery.GetVersions:output_type -> cloudquery.discovery.v1.GetVersions.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_pb_discovery_v1_discovery_proto_init() }
func file_plugin_pb_discovery_v1_discovery_proto_init() {
	if File_plugin_pb_discovery_v1_discovery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_discovery_v1_discovery_proto_rawDesc), len(file_plugin_pb_discovery_v1_discovery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_discovery_v1_discovery_proto_goTypes,
		DependencyIndexes: file_plugin_pb_discovery_v1_discovery_proto_depIdxs,
		MessageInfos:      file_plugin_pb_discovery_v1_discovery_proto_msgTypes,
	}.Build()
	File_plugin_pb_discovery_v1_discovery_proto = out.File
	file_plugin_pb_discovery_v1_discovery_proto_goTypes = nil
	file_plugin_pb_discovery_v1_discovery_proto_depIdxs = nil
}
