// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.23.4
// source: plugin-pb/source/v2/source.proto

package source

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenDocs_FORMAT int32

const (
	GenDocs_markdown GenDocs_FORMAT = 0
	GenDocs_json     GenDocs_FORMAT = 1
)

// Enum value maps for GenDocs_FORMAT.
var (
	GenDocs_FORMAT_name = map[int32]string{
		0: "markdown",
		1: "json",
	}
	GenDocs_FORMAT_value = map[string]int32{
		"markdown": 0,
		"json":     1,
	}
)

func (x GenDocs_FORMAT) Enum() *GenDocs_FORMAT {
	p := new(GenDocs_FORMAT)
	*p = x
	return p
}

func (x GenDocs_FORMAT) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenDocs_FORMAT) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_pb_source_v2_source_proto_enumTypes[0].Descriptor()
}

func (GenDocs_FORMAT) Type() protoreflect.EnumType {
	return &file_plugin_pb_source_v2_source_proto_enumTypes[0]
}

func (x GenDocs_FORMAT) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenDocs_FORMAT.Descriptor instead.
func (GenDocs_FORMAT) EnumDescriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{7, 0}
}

type GetName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName) Reset() {
	*x = GetName{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName) ProtoMessage() {}

func (x *GetName) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName.ProtoReflect.Descriptor instead.
func (*GetName) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{0}
}

type GetVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion) Reset() {
	*x = GetVersion{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion) ProtoMessage() {}

func (x *GetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion.ProtoReflect.Descriptor instead.
func (*GetVersion) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{1}
}

type Init struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{2}
}

type GetDynamicTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicTables) Reset() {
	*x = GetDynamicTables{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicTables) ProtoMessage() {}

func (x *GetDynamicTables) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicTables.ProtoReflect.Descriptor instead.
func (*GetDynamicTables) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{3}
}

type Sync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{4}
}

type GetTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables) Reset() {
	*x = GetTables{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables) ProtoMessage() {}

func (x *GetTables) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables.ProtoReflect.Descriptor instead.
func (*GetTables) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{5}
}

type GetMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetrics) Reset() {
	*x = GetMetrics{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetrics) ProtoMessage() {}

func (x *GetMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetrics.ProtoReflect.Descriptor instead.
func (*GetMetrics) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{6}
}

type GenDocs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenDocs) Reset() {
	*x = GenDocs{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenDocs) ProtoMessage() {}

func (x *GenDocs) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenDocs.ProtoReflect.Descriptor instead.
func (*GenDocs) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{7}
}

type GetName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName_Request) Reset() {
	*x = GetName_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Request) ProtoMessage() {}

func (x *GetName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Request.ProtoReflect.Descriptor instead.
func (*GetName_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{0, 0}
}

type GetName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName_Response) Reset() {
	*x = GetName_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Response) ProtoMessage() {}

func (x *GetName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Response.ProtoReflect.Descriptor instead.
func (*GetName_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion_Request) Reset() {
	*x = GetVersion_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion_Request) ProtoMessage() {}

func (x *GetVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion_Request.ProtoReflect.Descriptor instead.
func (*GetVersion_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{1, 0}
}

type GetVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion_Response) Reset() {
	*x = GetVersion_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion_Response) ProtoMessage() {}

func (x *GetVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion_Response.ProtoReflect.Descriptor instead.
func (*GetVersion_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Init_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshaled specs.Source
	Spec          []byte `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init_Request) Reset() {
	*x = Init_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init_Request) ProtoMessage() {}

func (x *Init_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init_Request.ProtoReflect.Descriptor instead.
func (*Init_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{2, 0}
}

func (x *Init_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Init_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init_Response) Reset() {
	*x = Init_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init_Response) ProtoMessage() {}

func (x *Init_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init_Response.ProtoReflect.Descriptor instead.
func (*Init_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{2, 1}
}

type GetDynamicTables_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicTables_Request) Reset() {
	*x = GetDynamicTables_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicTables_Request) ProtoMessage() {}

func (x *GetDynamicTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicTables_Request.ProtoReflect.Descriptor instead.
func (*GetDynamicTables_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{3, 0}
}

type GetDynamicTables_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshaled []*schema.Table
	Tables        [][]byte `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDynamicTables_Response) Reset() {
	*x = GetDynamicTables_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDynamicTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDynamicTables_Response) ProtoMessage() {}

func (x *GetDynamicTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDynamicTables_Response.ProtoReflect.Descriptor instead.
func (*GetDynamicTables_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetDynamicTables_Response) GetTables() [][]byte {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Sync_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Request) Reset() {
	*x = Sync_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Request) ProtoMessage() {}

func (x *Sync_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Request.ProtoReflect.Descriptor instead.
func (*Sync_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Sync_Request) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

type Sync_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled *arrow.Records
	Resource      []byte `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Response) Reset() {
	*x = Sync_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Response) ProtoMessage() {}

func (x *Sync_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Response.ProtoReflect.Descriptor instead.
func (*Sync_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{4, 1}
}

func (x *Sync_Response) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetTables_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables_Request) Reset() {
	*x = GetTables_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Request) ProtoMessage() {}

func (x *GetTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Request.ProtoReflect.Descriptor instead.
func (*GetTables_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{5, 0}
}

type GetTables_Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Marshalled []arrow.Schema
	Tables        [][]byte `protobuf:"bytes,3,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables_Response) Reset() {
	*x = GetTables_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Response) ProtoMessage() {}

func (x *GetTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Response.ProtoReflect.Descriptor instead.
func (*GetTables_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetTables_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTables_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetTables_Response) GetTables() [][]byte {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetMetrics_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetrics_Request) Reset() {
	*x = GetMetrics_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetrics_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetrics_Request) ProtoMessage() {}

func (x *GetMetrics_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetrics_Request.ProtoReflect.Descriptor instead.
func (*GetMetrics_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{6, 0}
}

type GetMetrics_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled json of plugins.SourceMetrics
	Metrics       []byte `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetrics_Response) Reset() {
	*x = GetMetrics_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetrics_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetrics_Response) ProtoMessage() {}

func (x *GetMetrics_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetrics_Response.ProtoReflect.Descriptor instead.
func (*GetMetrics_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetMetrics_Response) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GenDocs_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Format        GenDocs_FORMAT         `protobuf:"varint,2,opt,name=format,proto3,enum=cloudquery.source.v2.GenDocs_FORMAT" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenDocs_Request) Reset() {
	*x = GenDocs_Request{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenDocs_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenDocs_Request) ProtoMessage() {}

func (x *GenDocs_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenDocs_Request.ProtoReflect.Descriptor instead.
func (*GenDocs_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GenDocs_Request) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GenDocs_Request) GetFormat() GenDocs_FORMAT {
	if x != nil {
		return x.Format
	}
	return GenDocs_markdown
}

type GenDocs_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenDocs_Response) Reset() {
	*x = GenDocs_Response{}
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenDocs_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenDocs_Response) ProtoMessage() {}

func (x *GenDocs_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v2_source_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenDocs_Response.ProtoReflect.Descriptor instead.
func (*GenDocs_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v2_source_proto_rawDescGZIP(), []int{7, 1}
}

var File_plugin_pb_source_v2_source_proto protoreflect.FileDescriptor

const file_plugin_pb_source_v2_source_proto_rawDesc = "" +
	"\n" +
	" plugin-pb/source/v2/source.proto\x12\x14cloudquery.source.v2\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\aGetName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\n" +
	"GetVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"1\n" +
	"\x04Init\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x1a\n" +
	"\n" +
	"\bResponse\"A\n" +
	"\x10GetDynamicTables\x1a\t\n" +
	"\aRequest\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\fR\x06tables\"r\n" +
	"\x04Sync\x1aB\n" +
	"\aRequest\x127\n" +
	"\tsync_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x1a&\n" +
	"\bResponse\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\fR\bresource\"h\n" +
	"\tGetTables\x1a\t\n" +
	"\aRequest\x1aP\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06tables\x18\x03 \x03(\fR\x06tables\"=\n" +
	"\n" +
	"GetMetrics\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\fR\ametrics\"\x94\x01\n" +
	"\aGenDocs\x1a[\n" +
	"\aRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12<\n" +
	"\x06format\x18\x02 \x01(\x0e2$.cloudquery.source.v2.GenDocs.FORMATR\x06format\x1a\n" +
	"\n" +
	"\bResponse\" \n" +
	"\x06FORMAT\x12\f\n" +
	"\bmarkdown\x10\x00\x12\b\n" +
	"\x04json\x10\x012\xfb\x05\n" +
	"\x06Source\x12X\n" +
	"\aGetName\x12%.cloudquery.source.v2.GetName.Request\x1a&.cloudquery.source.v2.GetName.Response\x12a\n" +
	"\n" +
	"GetVersion\x12(.cloudquery.source.v2.GetVersion.Request\x1a).cloudquery.source.v2.GetVersion.Response\x12^\n" +
	"\tGetTables\x12'.cloudquery.source.v2.GetTables.Request\x1a(.cloudquery.source.v2.GetTables.Response\x12a\n" +
	"\n" +
	"GetMetrics\x12(.cloudquery.source.v2.GetMetrics.Request\x1a).cloudquery.source.v2.GetMetrics.Response\x12O\n" +
	"\x04Init\x12\".cloudquery.source.v2.Init.Request\x1a#.cloudquery.source.v2.Init.Response\x12s\n" +
	"\x10GetDynamicTables\x12..cloudquery.source.v2.GetDynamicTables.Request\x1a/.cloudquery.source.v2.GetDynamicTables.Response\x12Q\n" +
	"\x04Sync\x12\".cloudquery.source.v2.Sync.Request\x1a#.cloudquery.source.v2.Sync.Response0\x01\x12X\n" +
	"\aGenDocs\x12%.cloudquery.source.v2.GenDocs.Request\x1a&.cloudquery.source.v2.GenDocs.ResponseB8Z6github.com/cloudquery/plugin-pb-go/pb/source/v2;sourceb\x06proto3"

var (
	file_plugin_pb_source_v2_source_proto_rawDescOnce sync.Once
	file_plugin_pb_source_v2_source_proto_rawDescData []byte
)

func file_plugin_pb_source_v2_source_proto_rawDescGZIP() []byte {
	file_plugin_pb_source_v2_source_proto_rawDescOnce.Do(func() {
		file_plugin_pb_source_v2_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_source_v2_source_proto_rawDesc), len(file_plugin_pb_source_v2_source_proto_rawDesc)))
	})
	return file_plugin_pb_source_v2_source_proto_rawDescData
}

var file_plugin_pb_source_v2_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_pb_source_v2_source_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_plugin_pb_source_v2_source_proto_goTypes = []any{
	(GenDocs_FORMAT)(0),               // 0: cloudquery.source.v2.GenDocs.FORMAT
	(*GetName)(nil),                   // 1: cloudquery.source.v2.GetName
	(*GetVersion)(nil),                // 2: cloudquery.source.v2.GetVersion
	(*Init)(nil),                      // 3: cloudquery.source.v2.Init
	(*GetDynamicTables)(nil),          // 4: cloudquery.source.v2.GetDynamicTables
	(*Sync)(nil),                      // 5: cloudquery.source.v2.Sync
	(*GetTables)(nil),                 // 6: cloudquery.source.v2.GetTables
	(*GetMetrics)(nil),                // 7: cloudquery.source.v2.GetMetrics
	(*GenDocs)(nil),                   // 8: cloudquery.source.v2.GenDocs
	(*GetName_Request)(nil),           // 9: cloudquery.source.v2.GetName.Request
	(*GetName_Response)(nil),          // 10: cloudquery.source.v2.GetName.Response
	(*GetVersion_Request)(nil),        // 11: cloudquery.source.v2.GetVersion.Request
	(*GetVersion_Response)(nil),       // 12: cloudquery.source.v2.GetVersion.Response
	(*Init_Request)(nil),              // 13: cloudquery.source.v2.Init.Request
	(*Init_Response)(nil),             // 14: cloudquery.source.v2.Init.Response
	(*GetDynamicTables_Request)(nil),  // 15: cloudquery.source.v2.GetDynamicTables.Request
	(*GetDynamicTables_Response)(nil), // 16: cloudquery.source.v2.GetDynamicTables.Response
	(*Sync_Request)(nil),              // 17: cloudquery.source.v2.Sync.Request
	(*Sync_Response)(nil),             // 18: cloudquery.source.v2.Sync.Response
	(*GetTables_Request)(nil),         // 19: cloudquery.source.v2.GetTables.Request
	(*GetTables_Response)(nil),        // 20: cloudquery.source.v2.GetTables.Response
	(*GetMetrics_Request)(nil),        // 21: cloudquery.source.v2.GetMetrics.Request
	(*GetMetrics_Response)(nil),       // 22: cloudquery.source.v2.GetMetrics.Response
	(*GenDocs_Request)(nil),           // 23: cloudquery.source.v2.GenDocs.Request
	(*GenDocs_Response)(nil),          // 24: cloudquery.source.v2.GenDocs.Response
	(*timestamppb.Timestamp)(nil),     // 25: google.protobuf.Timestamp
}
var file_plugin_pb_source_v2_source_proto_depIdxs = []int32{
	25, // 0: cloudquery.source.v2.Sync.Request.sync_time:type_name -> google.protobuf.Timestamp
	0,  // 1: cloudquery.source.v2.GenDocs.Request.format:type_name -> cloudquery.source.v2.GenDocs.FORMAT
	9,  // 2: cloudquery.source.v2.Source.GetName:input_type -> cloudquery.source.v2.GetName.Request
	11, // 3: cloudquery.source.v2.Source.GetVersion:input_type -> cloudquery.source.v2.GetVersion.Request
	19, // 4: cloudquery.source.v2.Source.GetTables:input_type -> cloudquery.source.v2.GetTables.Request
	21, // 5: cloudquery.source.v2.Source.GetMetrics:input_type -> cloudquery.source.v2.GetMetrics.Request
	13, // 6: cloudquery.source.v2.Source.Init:input_type -> cloudquery.source.v2.Init.Request
	15, // 7: cloudquery.source.v2.Source.GetDynamicTables:input_type -> cloudquery.source.v2.GetDynamicTables.Request
	17, // 8: cloudquery.source.v2.Source.Sync:input_type -> cloudquery.source.v2.Sync.Request
	23, // 9: cloudquery.source.v2.Source.GenDocs:input_type -> cloudquery.source.v2.GenDocs.Request
	10, // 10: cloudquery.source.v2.Source.GetName:output_type -> cloudquery.source.v2.GetName.Response
	12, // 11: cloudquery.source.v2.Source.GetVersion:output_type -> cloudquery.source.v2.GetVersion.Response
	20, // 12: cloudquery.source.v2.Source.GetTables:output_type -> cloudquery.source.v2.GetTables.Response
	22, // 13: cloudquery.source.v2.Source.GetMetrics:output_type -> cloudquery.source.v2.GetMetrics.Response
	14, // 14: cloudquery.source.v2.Source.Init:output_type -> cloudquery.source.v2.Init.Response
	16, // 15: cloudquery.source.v2.Source.GetDynamicTables:output_type -> cloudquery.source.v2.GetDynamicTables.Response
	18, // 16: cloudquery.source.v2.Source.Sync:output_type -> cloudquery.source.v2.Sync.Response
	24, // 17: cloudquery.source.v2.Source.GenDocs:output_type -> cloudquery.source.v2.GenDocs.Response
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_plugin_pb_source_v2_source_proto_init() }
func file_plugin_pb_source_v2_source_proto_init() {
	if File_plugin_pb_source_v2_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_source_v2_source_proto_rawDesc), len(file_plugin_pb_source_v2_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_source_v2_source_proto_goTypes,
		DependencyIndexes: file_plugin_pb_source_v2_source_proto_depIdxs,
		EnumInfos:         file_plugin_pb_source_v2_source_proto_enumTypes,
		MessageInfos:      file_plugin_pb_source_v2_source_proto_msgTypes,
	}.Build()
	File_plugin_pb_source_v2_source_proto = out.File
	file_plugin_pb_source_v2_source_proto_goTypes = nil
	file_plugin_pb_source_v2_source_proto_depIdxs = nil
}
