// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: plugin-pb/source/v0/source.proto

package source

import (
	v0 "github.com/cloudquery/plugin-pb-go/pb/base/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{0}
}

type Sync2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync2) Reset() {
	*x = Sync2{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync2) ProtoMessage() {}

func (x *Sync2) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync2.ProtoReflect.Descriptor instead.
func (*Sync2) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{1}
}

type GetSyncSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncSummary) Reset() {
	*x = GetSyncSummary{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncSummary) ProtoMessage() {}

func (x *GetSyncSummary) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncSummary.ProtoReflect.Descriptor instead.
func (*GetSyncSummary) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{2}
}

type GetTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables) Reset() {
	*x = GetTables{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables) ProtoMessage() {}

func (x *GetTables) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables.ProtoReflect.Descriptor instead.
func (*GetTables) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{3}
}

type GetTablesForSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTablesForSpec) Reset() {
	*x = GetTablesForSpec{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTablesForSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesForSpec) ProtoMessage() {}

func (x *GetTablesForSpec) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesForSpec.ProtoReflect.Descriptor instead.
func (*GetTablesForSpec) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{4}
}

type GetSourceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceMetrics) Reset() {
	*x = GetSourceMetrics{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceMetrics) ProtoMessage() {}

func (x *GetSourceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceMetrics.ProtoReflect.Descriptor instead.
func (*GetSourceMetrics) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{5}
}

type Sync_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Spec  []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// sync timestamp
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Request) Reset() {
	*x = Sync_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Request) ProtoMessage() {}

func (x *Sync_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Request.ProtoReflect.Descriptor instead.
func (*Sync_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Sync_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Sync_Request) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Sync_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled *schema.Resources
	Resource      []byte `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Response) Reset() {
	*x = Sync_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Response) ProtoMessage() {}

func (x *Sync_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Response.ProtoReflect.Descriptor instead.
func (*Sync_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Sync_Response) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

type Sync2_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync2_Request) Reset() {
	*x = Sync2_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync2_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync2_Request) ProtoMessage() {}

func (x *Sync2_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync2_Request.ProtoReflect.Descriptor instead.
func (*Sync2_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Sync2_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type Sync2_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled *schema.Resources
	Resource      []byte `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync2_Response) Reset() {
	*x = Sync2_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync2_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync2_Response) ProtoMessage() {}

func (x *Sync2_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync2_Response.ProtoReflect.Descriptor instead.
func (*Sync2_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Sync2_Response) GetResource() []byte {
	if x != nil {
		return x.Resource
	}
	return nil
}

type GetSyncSummary_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncSummary_Request) Reset() {
	*x = GetSyncSummary_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncSummary_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncSummary_Request) ProtoMessage() {}

func (x *GetSyncSummary_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncSummary_Request.ProtoReflect.Descriptor instead.
func (*GetSyncSummary_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{2, 0}
}

type GetSyncSummary_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled *schema.SyncSummary
	Summary       []byte `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncSummary_Response) Reset() {
	*x = GetSyncSummary_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncSummary_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncSummary_Response) ProtoMessage() {}

func (x *GetSyncSummary_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncSummary_Response.ProtoReflect.Descriptor instead.
func (*GetSyncSummary_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetSyncSummary_Response) GetSummary() []byte {
	if x != nil {
		return x.Summary
	}
	return nil
}

type GetTables_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables_Request) Reset() {
	*x = GetTables_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Request) ProtoMessage() {}

func (x *GetTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Request.ProtoReflect.Descriptor instead.
func (*GetTables_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{3, 0}
}

type GetTables_Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Marshalled []*schema.Table
	Tables        []byte `protobuf:"bytes,3,opt,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables_Response) Reset() {
	*x = GetTables_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Response) ProtoMessage() {}

func (x *GetTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Response.ProtoReflect.Descriptor instead.
func (*GetTables_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetTables_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTables_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetTables_Response) GetTables() []byte {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetTablesForSpec_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Marshalled specs.Source
	Spec          []byte `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTablesForSpec_Request) Reset() {
	*x = GetTablesForSpec_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTablesForSpec_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesForSpec_Request) ProtoMessage() {}

func (x *GetTablesForSpec_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesForSpec_Request.ProtoReflect.Descriptor instead.
func (*GetTablesForSpec_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTablesForSpec_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type GetTablesForSpec_Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Marshalled []*schema.Table
	Tables        []byte `protobuf:"bytes,3,opt,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTablesForSpec_Response) Reset() {
	*x = GetTablesForSpec_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTablesForSpec_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesForSpec_Response) ProtoMessage() {}

func (x *GetTablesForSpec_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesForSpec_Response.ProtoReflect.Descriptor instead.
func (*GetTablesForSpec_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetTablesForSpec_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTablesForSpec_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetTablesForSpec_Response) GetTables() []byte {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetSourceMetrics_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceMetrics_Request) Reset() {
	*x = GetSourceMetrics_Request{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceMetrics_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceMetrics_Request) ProtoMessage() {}

func (x *GetSourceMetrics_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceMetrics_Request.ProtoReflect.Descriptor instead.
func (*GetSourceMetrics_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{5, 0}
}

type GetSourceMetrics_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled json of plugins.SourceMetrics
	Metrics       []byte `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceMetrics_Response) Reset() {
	*x = GetSourceMetrics_Response{}
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceMetrics_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceMetrics_Response) ProtoMessage() {}

func (x *GetSourceMetrics_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_source_v0_source_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceMetrics_Response.ProtoReflect.Descriptor instead.
func (*GetSourceMetrics_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_source_v0_source_proto_rawDescGZIP(), []int{5, 1}
}

func (x *GetSourceMetrics_Response) GetMetrics() []byte {
	if x != nil {
		return x.Metrics
	}
	return nil
}

var File_plugin_pb_source_v0_source_proto protoreflect.FileDescriptor

const file_plugin_pb_source_v0_source_proto_rawDesc = "" +
	"\n" +
	" plugin-pb/source/v0/source.proto\x12\x05proto\x1a\x1cplugin-pb/base/v0/base.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\x04Sync\x1aW\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a&\n" +
	"\bResponse\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\fR\bresource\"N\n" +
	"\x05Sync2\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x1a&\n" +
	"\bResponse\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\fR\bresource\"A\n" +
	"\x0eGetSyncSummary\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\fR\asummary\"h\n" +
	"\tGetTables\x1a\t\n" +
	"\aRequest\x1aP\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06tables\x18\x03 \x01(\fR\x06tables\"\x83\x01\n" +
	"\x10GetTablesForSpec\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x1aP\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06tables\x18\x03 \x01(\fR\x06tables\"C\n" +
	"\x10GetSourceMetrics\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\ametrics\x18\x01 \x01(\fR\ametrics2\x8e\x05\n" +
	"\x06Source\x12[\n" +
	"\x12GetProtocolVersion\x12!.proto.GetProtocolVersion.Request\x1a\".proto.GetProtocolVersion.Response\x12:\n" +
	"\aGetName\x12\x16.proto.GetName.Request\x1a\x17.proto.GetName.Response\x12C\n" +
	"\n" +
	"GetVersion\x12\x19.proto.GetVersion.Request\x1a\x1a.proto.GetVersion.Response\x12@\n" +
	"\tGetTables\x12\x18.proto.GetTables.Request\x1a\x19.proto.GetTables.Response\x12U\n" +
	"\x10GetTablesForSpec\x12\x1f.proto.GetTablesForSpec.Request\x1a .proto.GetTablesForSpec.Response\x12O\n" +
	"\x0eGetSyncSummary\x12\x1d.proto.GetSyncSummary.Request\x1a\x1e.proto.GetSyncSummary.Response\x123\n" +
	"\x04Sync\x12\x13.proto.Sync.Request\x1a\x14.proto.Sync.Response0\x01\x126\n" +
	"\x05Sync2\x12\x14.proto.Sync2.Request\x1a\x15.proto.Sync2.Response0\x01\x12O\n" +
	"\n" +
	"GetMetrics\x12\x1f.proto.GetSourceMetrics.Request\x1a .proto.GetSourceMetrics.ResponseB8Z6github.com/cloudquery/plugin-pb-go/pb/source/v0;sourceb\x06proto3"

var (
	file_plugin_pb_source_v0_source_proto_rawDescOnce sync.Once
	file_plugin_pb_source_v0_source_proto_rawDescData []byte
)

func file_plugin_pb_source_v0_source_proto_rawDescGZIP() []byte {
	file_plugin_pb_source_v0_source_proto_rawDescOnce.Do(func() {
		file_plugin_pb_source_v0_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_source_v0_source_proto_rawDesc), len(file_plugin_pb_source_v0_source_proto_rawDesc)))
	})
	return file_plugin_pb_source_v0_source_proto_rawDescData
}

var file_plugin_pb_source_v0_source_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_plugin_pb_source_v0_source_proto_goTypes = []any{
	(*Sync)(nil),                           // 0: proto.Sync
	(*Sync2)(nil),                          // 1: proto.Sync2
	(*GetSyncSummary)(nil),                 // 2: proto.GetSyncSummary
	(*GetTables)(nil),                      // 3: proto.GetTables
	(*GetTablesForSpec)(nil),               // 4: proto.GetTablesForSpec
	(*GetSourceMetrics)(nil),               // 5: proto.GetSourceMetrics
	(*Sync_Request)(nil),                   // 6: proto.Sync.Request
	(*Sync_Response)(nil),                  // 7: proto.Sync.Response
	(*Sync2_Request)(nil),                  // 8: proto.Sync2.Request
	(*Sync2_Response)(nil),                 // 9: proto.Sync2.Response
	(*GetSyncSummary_Request)(nil),         // 10: proto.GetSyncSummary.Request
	(*GetSyncSummary_Response)(nil),        // 11: proto.GetSyncSummary.Response
	(*GetTables_Request)(nil),              // 12: proto.GetTables.Request
	(*GetTables_Response)(nil),             // 13: proto.GetTables.Response
	(*GetTablesForSpec_Request)(nil),       // 14: proto.GetTablesForSpec.Request
	(*GetTablesForSpec_Response)(nil),      // 15: proto.GetTablesForSpec.Response
	(*GetSourceMetrics_Request)(nil),       // 16: proto.GetSourceMetrics.Request
	(*GetSourceMetrics_Response)(nil),      // 17: proto.GetSourceMetrics.Response
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
	(*v0.GetProtocolVersion_Request)(nil),  // 19: proto.GetProtocolVersion.Request
	(*v0.GetName_Request)(nil),             // 20: proto.GetName.Request
	(*v0.GetVersion_Request)(nil),          // 21: proto.GetVersion.Request
	(*v0.GetProtocolVersion_Response)(nil), // 22: proto.GetProtocolVersion.Response
	(*v0.GetName_Response)(nil),            // 23: proto.GetName.Response
	(*v0.GetVersion_Response)(nil),         // 24: proto.GetVersion.Response
}
var file_plugin_pb_source_v0_source_proto_depIdxs = []int32{
	18, // 0: proto.Sync.Request.timestamp:type_name -> google.protobuf.Timestamp
	19, // 1: proto.Source.GetProtocolVersion:input_type -> proto.GetProtocolVersion.Request
	20, // 2: proto.Source.GetName:input_type -> proto.GetName.Request
	21, // 3: proto.Source.GetVersion:input_type -> proto.GetVersion.Request
	12, // 4: proto.Source.GetTables:input_type -> proto.GetTables.Request
	14, // 5: proto.Source.GetTablesForSpec:input_type -> proto.GetTablesForSpec.Request
	10, // 6: proto.Source.GetSyncSummary:input_type -> proto.GetSyncSummary.Request
	6,  // 7: proto.Source.Sync:input_type -> proto.Sync.Request
	8,  // 8: proto.Source.Sync2:input_type -> proto.Sync2.Request
	16, // 9: proto.Source.GetMetrics:input_type -> proto.GetSourceMetrics.Request
	22, // 10: proto.Source.GetProtocolVersion:output_type -> proto.GetProtocolVersion.Response
	23, // 11: proto.Source.GetName:output_type -> proto.GetName.Response
	24, // 12: proto.Source.GetVersion:output_type -> proto.GetVersion.Response
	13, // 13: proto.Source.GetTables:output_type -> proto.GetTables.Response
	15, // 14: proto.Source.GetTablesForSpec:output_type -> proto.GetTablesForSpec.Response
	11, // 15: proto.Source.GetSyncSummary:output_type -> proto.GetSyncSummary.Response
	7,  // 16: proto.Source.Sync:output_type -> proto.Sync.Response
	9,  // 17: proto.Source.Sync2:output_type -> proto.Sync2.Response
	17, // 18: proto.Source.GetMetrics:output_type -> proto.GetSourceMetrics.Response
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_plugin_pb_source_v0_source_proto_init() }
func file_plugin_pb_source_v0_source_proto_init() {
	if File_plugin_pb_source_v0_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_source_v0_source_proto_rawDesc), len(file_plugin_pb_source_v0_source_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_source_v0_source_proto_goTypes,
		DependencyIndexes: file_plugin_pb_source_v0_source_proto_depIdxs,
		MessageInfos:      file_plugin_pb_source_v0_source_proto_msgTypes,
	}.Build()
	File_plugin_pb_source_v0_source_proto = out.File
	file_plugin_pb_source_v0_source_proto_goTypes = nil
	file_plugin_pb_source_v0_source_proto_depIdxs = nil
}
