// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v4.23.4
// source: plugin-pb/plugin/v3/plugin.proto

package plugin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Predicate_Operator int32

const (
	Predicate_EQ Predicate_Operator = 0
)

// Enum value maps for Predicate_Operator.
var (
	Predicate_Operator_name = map[int32]string{
		0: "EQ",
	}
	Predicate_Operator_value = map[string]int32{
		"EQ": 0,
	}
)

func (x Predicate_Operator) Enum() *Predicate_Operator {
	p := new(Predicate_Operator)
	*p = x
	return p
}

func (x Predicate_Operator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Predicate_Operator) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_pb_plugin_v3_plugin_proto_enumTypes[0].Descriptor()
}

func (Predicate_Operator) Type() protoreflect.EnumType {
	return &file_plugin_pb_plugin_v3_plugin_proto_enumTypes[0]
}

func (x Predicate_Operator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Predicate_Operator.Descriptor instead.
func (Predicate_Operator) EnumDescriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{8, 0}
}

type PredicatesGroup_GroupingType int32

const (
	PredicatesGroup_AND PredicatesGroup_GroupingType = 0
	PredicatesGroup_OR  PredicatesGroup_GroupingType = 1
)

// Enum value maps for PredicatesGroup_GroupingType.
var (
	PredicatesGroup_GroupingType_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	PredicatesGroup_GroupingType_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x PredicatesGroup_GroupingType) Enum() *PredicatesGroup_GroupingType {
	p := new(PredicatesGroup_GroupingType)
	*p = x
	return p
}

func (x PredicatesGroup_GroupingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PredicatesGroup_GroupingType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_pb_plugin_v3_plugin_proto_enumTypes[1].Descriptor()
}

func (PredicatesGroup_GroupingType) Type() protoreflect.EnumType {
	return &file_plugin_pb_plugin_v3_plugin_proto_enumTypes[1]
}

func (x PredicatesGroup_GroupingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PredicatesGroup_GroupingType.Descriptor instead.
func (PredicatesGroup_GroupingType) EnumDescriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{9, 0}
}

type GetName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName) Reset() {
	*x = GetName{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName) ProtoMessage() {}

func (x *GetName) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName.ProtoReflect.Descriptor instead.
func (*GetName) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{0}
}

type GetVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion) Reset() {
	*x = GetVersion{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion) ProtoMessage() {}

func (x *GetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion.ProtoReflect.Descriptor instead.
func (*GetVersion) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{1}
}

type GetSpecSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecSchema) Reset() {
	*x = GetSpecSchema{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecSchema) ProtoMessage() {}

func (x *GetSpecSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecSchema.ProtoReflect.Descriptor instead.
func (*GetSpecSchema) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{2}
}

type Init struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init) Reset() {
	*x = Init{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init) ProtoMessage() {}

func (x *Init) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init.ProtoReflect.Descriptor instead.
func (*Init) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{3}
}

type GetTables struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables) Reset() {
	*x = GetTables{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables) ProtoMessage() {}

func (x *GetTables) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables.ProtoReflect.Descriptor instead.
func (*GetTables) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{4}
}

type Sync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync) Reset() {
	*x = Sync{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync) ProtoMessage() {}

func (x *Sync) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync.ProtoReflect.Descriptor instead.
func (*Sync) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5}
}

type Read struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read) Reset() {
	*x = Read{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read) ProtoMessage() {}

func (x *Read) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read.ProtoReflect.Descriptor instead.
func (*Read) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{6}
}

type TableRelation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	ParentTable   string                 `protobuf:"bytes,2,opt,name=parent_table,json=parentTable,proto3" json:"parent_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRelation) Reset() {
	*x = TableRelation{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRelation) ProtoMessage() {}

func (x *TableRelation) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRelation.ProtoReflect.Descriptor instead.
func (*TableRelation) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *TableRelation) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *TableRelation) GetParentTable() string {
	if x != nil {
		return x.ParentTable
	}
	return ""
}

type Predicate struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Operator Predicate_Operator     `protobuf:"varint,1,opt,name=operator,proto3,enum=cloudquery.plugin.v3.Predicate_Operator" json:"operator,omitempty"`
	Column   string                 `protobuf:"bytes,2,opt,name=column,proto3" json:"column,omitempty"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Predicate) GetOperator() Predicate_Operator {
	if x != nil {
		return x.Operator
	}
	return Predicate_EQ
}

func (x *Predicate) GetColumn() string {
	if x != nil {
		return x.Column
	}
	return ""
}

func (x *Predicate) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type PredicatesGroup struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	GroupingType  PredicatesGroup_GroupingType `protobuf:"varint,1,opt,name=grouping_type,json=groupingType,proto3,enum=cloudquery.plugin.v3.PredicatesGroup_GroupingType" json:"grouping_type,omitempty"`
	Predicates    []*Predicate                 `protobuf:"bytes,2,rep,name=predicates,proto3" json:"predicates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredicatesGroup) Reset() {
	*x = PredicatesGroup{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredicatesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredicatesGroup) ProtoMessage() {}

func (x *PredicatesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredicatesGroup.ProtoReflect.Descriptor instead.
func (*PredicatesGroup) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *PredicatesGroup) GetGroupingType() PredicatesGroup_GroupingType {
	if x != nil {
		return x.GroupingType
	}
	return PredicatesGroup_AND
}

func (x *PredicatesGroup) GetPredicates() []*Predicate {
	if x != nil {
		return x.Predicates
	}
	return nil
}

type Write struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write) Reset() {
	*x = Write{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write) ProtoMessage() {}

func (x *Write) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write.ProtoReflect.Descriptor instead.
func (*Write) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10}
}

type Transform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform) Reset() {
	*x = Transform{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform) ProtoMessage() {}

func (x *Transform) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform.ProtoReflect.Descriptor instead.
func (*Transform) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{11}
}

type TransformSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformSchema) Reset() {
	*x = TransformSchema{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformSchema) ProtoMessage() {}

func (x *TransformSchema) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformSchema.ProtoReflect.Descriptor instead.
func (*TransformSchema) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{12}
}

type Close struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close) Reset() {
	*x = Close{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close) ProtoMessage() {}

func (x *Close) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close.ProtoReflect.Descriptor instead.
func (*Close) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{13}
}

type TestConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnection) Reset() {
	*x = TestConnection{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnection) ProtoMessage() {}

func (x *TestConnection) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnection.ProtoReflect.Descriptor instead.
func (*TestConnection) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{14}
}

type GetName_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName_Request) Reset() {
	*x = GetName_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Request) ProtoMessage() {}

func (x *GetName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Request.ProtoReflect.Descriptor instead.
func (*GetName_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{0, 0}
}

type GetName_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetName_Response) Reset() {
	*x = GetName_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetName_Response) ProtoMessage() {}

func (x *GetName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetName_Response.ProtoReflect.Descriptor instead.
func (*GetName_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetVersion_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion_Request) Reset() {
	*x = GetVersion_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion_Request) ProtoMessage() {}

func (x *GetVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion_Request.ProtoReflect.Descriptor instead.
func (*GetVersion_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{1, 0}
}

type GetVersion_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersion_Response) Reset() {
	*x = GetVersion_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersion_Response) ProtoMessage() {}

func (x *GetVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersion_Response.ProtoReflect.Descriptor instead.
func (*GetVersion_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetSpecSchema_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecSchema_Request) Reset() {
	*x = GetSpecSchema_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecSchema_Request) ProtoMessage() {}

func (x *GetSpecSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecSchema_Request.ProtoReflect.Descriptor instead.
func (*GetSpecSchema_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{2, 0}
}

type GetSpecSchema_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Should be a valid JSON schema for the plugin spec.
	// See https://json-schema.org for more details.
	JsonSchema    *string `protobuf:"bytes,1,opt,name=json_schema,json=jsonSchema,proto3,oneof" json:"json_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecSchema_Response) Reset() {
	*x = GetSpecSchema_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecSchema_Response) ProtoMessage() {}

func (x *GetSpecSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecSchema_Response.ProtoReflect.Descriptor instead.
func (*GetSpecSchema_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetSpecSchema_Response) GetJsonSchema() string {
	if x != nil && x.JsonSchema != nil {
		return *x.JsonSchema
	}
	return ""
}

type Init_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`                                      // Internal plugin-specific spec
	NoConnection  bool                   `protobuf:"varint,2,opt,name=no_connection,json=noConnection,proto3" json:"no_connection,omitempty"` // A flag to indicate plugins should skip establishing a connection
	InvocationId  string                 `protobuf:"bytes,3,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`  // unique execution_id that will identify the invocation (sync, migrate etc)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init_Request) Reset() {
	*x = Init_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init_Request) ProtoMessage() {}

func (x *Init_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init_Request.ProtoReflect.Descriptor instead.
func (*Init_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Init_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Init_Request) GetNoConnection() bool {
	if x != nil {
		return x.NoConnection
	}
	return false
}

func (x *Init_Request) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

type Init_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Init_Response) Reset() {
	*x = Init_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Init_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Init_Response) ProtoMessage() {}

func (x *Init_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Init_Response.ProtoReflect.Descriptor instead.
func (*Init_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{3, 1}
}

type GetTables_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Tables              []string               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	SkipTables          []string               `protobuf:"bytes,2,rep,name=skip_tables,json=skipTables,proto3" json:"skip_tables,omitempty"`
	SkipDependentTables bool                   `protobuf:"varint,3,opt,name=skip_dependent_tables,json=skipDependentTables,proto3" json:"skip_dependent_tables,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetTables_Request) Reset() {
	*x = GetTables_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Request) ProtoMessage() {}

func (x *GetTables_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Request.ProtoReflect.Descriptor instead.
func (*GetTables_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetTables_Request) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *GetTables_Request) GetSkipTables() []string {
	if x != nil {
		return x.SkipTables
	}
	return nil
}

func (x *GetTables_Request) GetSkipDependentTables() bool {
	if x != nil {
		return x.SkipDependentTables
	}
	return false
}

type GetTables_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled []arrow.Schema
	Tables        [][]byte `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTables_Response) Reset() {
	*x = GetTables_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTables_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTables_Response) ProtoMessage() {}

func (x *GetTables_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTables_Response.ProtoReflect.Descriptor instead.
func (*GetTables_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetTables_Response) GetTables() [][]byte {
	if x != nil {
		return x.Tables
	}
	return nil
}

type Sync_MessageInsert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_MessageInsert) Reset() {
	*x = Sync_MessageInsert{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_MessageInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_MessageInsert) ProtoMessage() {}

func (x *Sync_MessageInsert) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_MessageInsert.ProtoReflect.Descriptor instead.
func (*Sync_MessageInsert) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Sync_MessageInsert) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type Sync_MessageMigrateTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	Table         []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_MessageMigrateTable) Reset() {
	*x = Sync_MessageMigrateTable{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_MessageMigrateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_MessageMigrateTable) ProtoMessage() {}

func (x *Sync_MessageMigrateTable) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_MessageMigrateTable.ProtoReflect.Descriptor instead.
func (*Sync_MessageMigrateTable) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Sync_MessageMigrateTable) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

type Sync_MessageDeleteRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TableName      string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	WhereClause    []*PredicatesGroup     `protobuf:"bytes,2,rep,name=where_clause,json=whereClause,proto3" json:"where_clause,omitempty"`
	TableRelations []*TableRelation       `protobuf:"bytes,3,rep,name=table_relations,json=tableRelations,proto3" json:"table_relations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Sync_MessageDeleteRecord) Reset() {
	*x = Sync_MessageDeleteRecord{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_MessageDeleteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_MessageDeleteRecord) ProtoMessage() {}

func (x *Sync_MessageDeleteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_MessageDeleteRecord.ProtoReflect.Descriptor instead.
func (*Sync_MessageDeleteRecord) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Sync_MessageDeleteRecord) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Sync_MessageDeleteRecord) GetWhereClause() []*PredicatesGroup {
	if x != nil {
		return x.WhereClause
	}
	return nil
}

func (x *Sync_MessageDeleteRecord) GetTableRelations() []*TableRelation {
	if x != nil {
		return x.TableRelations
	}
	return nil
}

type Sync_MessageError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_MessageError) Reset() {
	*x = Sync_MessageError{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_MessageError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_MessageError) ProtoMessage() {}

func (x *Sync_MessageError) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_MessageError.ProtoReflect.Descriptor instead.
func (*Sync_MessageError) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 3}
}

func (x *Sync_MessageError) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Sync_MessageError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Sync_BackendOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table name to use for state backend
	TableName string `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// connection path to use for state backend
	Connection    string `protobuf:"bytes,2,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_BackendOptions) Reset() {
	*x = Sync_BackendOptions{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_BackendOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_BackendOptions) ProtoMessage() {}

func (x *Sync_BackendOptions) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_BackendOptions.ProtoReflect.Descriptor instead.
func (*Sync_BackendOptions) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 4}
}

func (x *Sync_BackendOptions) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Sync_BackendOptions) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

type Sync_Request struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Tables              []string               `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	SkipTables          []string               `protobuf:"bytes,2,rep,name=skip_tables,json=skipTables,proto3" json:"skip_tables,omitempty"`
	SkipDependentTables bool                   `protobuf:"varint,3,opt,name=skip_dependent_tables,json=skipDependentTables,proto3" json:"skip_dependent_tables,omitempty"`
	DeterministicCqId   bool                   `protobuf:"varint,4,opt,name=deterministic_cq_id,json=deterministicCqId,proto3" json:"deterministic_cq_id,omitempty"`
	Backend             *Sync_BackendOptions   `protobuf:"bytes,5,opt,name=backend,proto3" json:"backend,omitempty"`
	Shard               *Sync_Request_Shard    `protobuf:"bytes,6,opt,name=shard,proto3,oneof" json:"shard,omitempty"`
	WithErrorMessages   bool                   `protobuf:"varint,7,opt,name=withErrorMessages,proto3" json:"withErrorMessages,omitempty"` // If true, the plugin will send error messages in the response stream
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Sync_Request) Reset() {
	*x = Sync_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Request) ProtoMessage() {}

func (x *Sync_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Request.ProtoReflect.Descriptor instead.
func (*Sync_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 5}
}

func (x *Sync_Request) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *Sync_Request) GetSkipTables() []string {
	if x != nil {
		return x.SkipTables
	}
	return nil
}

func (x *Sync_Request) GetSkipDependentTables() bool {
	if x != nil {
		return x.SkipDependentTables
	}
	return false
}

func (x *Sync_Request) GetDeterministicCqId() bool {
	if x != nil {
		return x.DeterministicCqId
	}
	return false
}

func (x *Sync_Request) GetBackend() *Sync_BackendOptions {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *Sync_Request) GetShard() *Sync_Request_Shard {
	if x != nil {
		return x.Shard
	}
	return nil
}

func (x *Sync_Request) GetWithErrorMessages() bool {
	if x != nil {
		return x.WithErrorMessages
	}
	return false
}

type Sync_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Sync_Response_MigrateTable
	//	*Sync_Response_Insert
	//	*Sync_Response_DeleteRecord
	//	*Sync_Response_Error
	Message       isSync_Response_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Response) Reset() {
	*x = Sync_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Response) ProtoMessage() {}

func (x *Sync_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Response.ProtoReflect.Descriptor instead.
func (*Sync_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 6}
}

func (x *Sync_Response) GetMessage() isSync_Response_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Sync_Response) GetMigrateTable() *Sync_MessageMigrateTable {
	if x != nil {
		if x, ok := x.Message.(*Sync_Response_MigrateTable); ok {
			return x.MigrateTable
		}
	}
	return nil
}

func (x *Sync_Response) GetInsert() *Sync_MessageInsert {
	if x != nil {
		if x, ok := x.Message.(*Sync_Response_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Sync_Response) GetDeleteRecord() *Sync_MessageDeleteRecord {
	if x != nil {
		if x, ok := x.Message.(*Sync_Response_DeleteRecord); ok {
			return x.DeleteRecord
		}
	}
	return nil
}

func (x *Sync_Response) GetError() *Sync_MessageError {
	if x != nil {
		if x, ok := x.Message.(*Sync_Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isSync_Response_Message interface {
	isSync_Response_Message()
}

type Sync_Response_MigrateTable struct {
	MigrateTable *Sync_MessageMigrateTable `protobuf:"bytes,1,opt,name=migrate_table,json=migrateTable,proto3,oneof"`
}

type Sync_Response_Insert struct {
	Insert *Sync_MessageInsert `protobuf:"bytes,2,opt,name=insert,proto3,oneof"`
}

type Sync_Response_DeleteRecord struct {
	DeleteRecord *Sync_MessageDeleteRecord `protobuf:"bytes,3,opt,name=delete_record,json=deleteRecord,proto3,oneof"`
}

type Sync_Response_Error struct {
	Error *Sync_MessageError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*Sync_Response_MigrateTable) isSync_Response_Message() {}

func (*Sync_Response_Insert) isSync_Response_Message() {}

func (*Sync_Response_DeleteRecord) isSync_Response_Message() {}

func (*Sync_Response_Error) isSync_Response_Message() {}

type Sync_Request_Shard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           int32                  `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sync_Request_Shard) Reset() {
	*x = Sync_Request_Shard{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sync_Request_Shard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sync_Request_Shard) ProtoMessage() {}

func (x *Sync_Request_Shard) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sync_Request_Shard.ProtoReflect.Descriptor instead.
func (*Sync_Request_Shard) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{5, 5, 0}
}

func (x *Sync_Request_Shard) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Sync_Request_Shard) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Read_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	Table         []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read_Request) Reset() {
	*x = Read_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read_Request) ProtoMessage() {}

func (x *Read_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read_Request.ProtoReflect.Descriptor instead.
func (*Read_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Read_Request) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

type Read_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Read_Response) Reset() {
	*x = Read_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Read_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Read_Response) ProtoMessage() {}

func (x *Read_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Read_Response.ProtoReflect.Descriptor instead.
func (*Read_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Read_Response) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type Write_MessageMigrateTable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	Table         []byte `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	MigrateForce  bool   `protobuf:"varint,2,opt,name=migrate_force,json=migrateForce,proto3" json:"migrate_force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write_MessageMigrateTable) Reset() {
	*x = Write_MessageMigrateTable{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_MessageMigrateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_MessageMigrateTable) ProtoMessage() {}

func (x *Write_MessageMigrateTable) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_MessageMigrateTable.ProtoReflect.Descriptor instead.
func (*Write_MessageMigrateTable) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 0}
}

func (x *Write_MessageMigrateTable) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Write_MessageMigrateTable) GetMigrateForce() bool {
	if x != nil {
		return x.MigrateForce
	}
	return false
}

type Write_MessageInsert struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write_MessageInsert) Reset() {
	*x = Write_MessageInsert{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_MessageInsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_MessageInsert) ProtoMessage() {}

func (x *Write_MessageInsert) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_MessageInsert.ProtoReflect.Descriptor instead.
func (*Write_MessageInsert) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 1}
}

func (x *Write_MessageInsert) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type Write_MessageDeleteStale struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	//
	// Deprecated: Marked as deprecated in plugin-pb/plugin/v3/plugin.proto.
	Table         []byte                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	SourceName    string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SyncTime      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sync_time,json=syncTime,proto3" json:"sync_time,omitempty"`
	TableName     string                 `protobuf:"bytes,4,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write_MessageDeleteStale) Reset() {
	*x = Write_MessageDeleteStale{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_MessageDeleteStale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_MessageDeleteStale) ProtoMessage() {}

func (x *Write_MessageDeleteStale) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_MessageDeleteStale.ProtoReflect.Descriptor instead.
func (*Write_MessageDeleteStale) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 2}
}

// Deprecated: Marked as deprecated in plugin-pb/plugin/v3/plugin.proto.
func (x *Write_MessageDeleteStale) GetTable() []byte {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *Write_MessageDeleteStale) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *Write_MessageDeleteStale) GetSyncTime() *timestamppb.Timestamp {
	if x != nil {
		return x.SyncTime
	}
	return nil
}

func (x *Write_MessageDeleteStale) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type Write_MessageDeleteRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TableName      string                 `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	WhereClause    []*PredicatesGroup     `protobuf:"bytes,2,rep,name=where_clause,json=whereClause,proto3" json:"where_clause,omitempty"`
	TableRelations []*TableRelation       `protobuf:"bytes,3,rep,name=table_relations,json=tableRelations,proto3" json:"table_relations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Write_MessageDeleteRecord) Reset() {
	*x = Write_MessageDeleteRecord{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_MessageDeleteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_MessageDeleteRecord) ProtoMessage() {}

func (x *Write_MessageDeleteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_MessageDeleteRecord.ProtoReflect.Descriptor instead.
func (*Write_MessageDeleteRecord) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 3}
}

func (x *Write_MessageDeleteRecord) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *Write_MessageDeleteRecord) GetWhereClause() []*PredicatesGroup {
	if x != nil {
		return x.WhereClause
	}
	return nil
}

func (x *Write_MessageDeleteRecord) GetTableRelations() []*TableRelation {
	if x != nil {
		return x.TableRelations
	}
	return nil
}

type Write_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Write_Request_MigrateTable
	//	*Write_Request_Insert
	//	*Write_Request_Delete
	//	*Write_Request_DeleteRecord
	Message       isWrite_Request_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write_Request) Reset() {
	*x = Write_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_Request) ProtoMessage() {}

func (x *Write_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_Request.ProtoReflect.Descriptor instead.
func (*Write_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 4}
}

func (x *Write_Request) GetMessage() isWrite_Request_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Write_Request) GetMigrateTable() *Write_MessageMigrateTable {
	if x != nil {
		if x, ok := x.Message.(*Write_Request_MigrateTable); ok {
			return x.MigrateTable
		}
	}
	return nil
}

func (x *Write_Request) GetInsert() *Write_MessageInsert {
	if x != nil {
		if x, ok := x.Message.(*Write_Request_Insert); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Write_Request) GetDelete() *Write_MessageDeleteStale {
	if x != nil {
		if x, ok := x.Message.(*Write_Request_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

func (x *Write_Request) GetDeleteRecord() *Write_MessageDeleteRecord {
	if x != nil {
		if x, ok := x.Message.(*Write_Request_DeleteRecord); ok {
			return x.DeleteRecord
		}
	}
	return nil
}

type isWrite_Request_Message interface {
	isWrite_Request_Message()
}

type Write_Request_MigrateTable struct {
	MigrateTable *Write_MessageMigrateTable `protobuf:"bytes,1,opt,name=migrate_table,json=migrateTable,proto3,oneof"`
}

type Write_Request_Insert struct {
	Insert *Write_MessageInsert `protobuf:"bytes,2,opt,name=insert,proto3,oneof"`
}

type Write_Request_Delete struct {
	Delete *Write_MessageDeleteStale `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

type Write_Request_DeleteRecord struct {
	DeleteRecord *Write_MessageDeleteRecord `protobuf:"bytes,4,opt,name=delete_record,json=deleteRecord,proto3,oneof"`
}

func (*Write_Request_MigrateTable) isWrite_Request_Message() {}

func (*Write_Request_Insert) isWrite_Request_Message() {}

func (*Write_Request_Delete) isWrite_Request_Message() {}

func (*Write_Request_DeleteRecord) isWrite_Request_Message() {}

type Write_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Write_Response) Reset() {
	*x = Write_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Write_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Write_Response) ProtoMessage() {}

func (x *Write_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Write_Response.ProtoReflect.Descriptor instead.
func (*Write_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{10, 5}
}

type Transform_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform_Request) Reset() {
	*x = Transform_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform_Request) ProtoMessage() {}

func (x *Transform_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform_Request.ProtoReflect.Descriptor instead.
func (*Transform_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{11, 0}
}

func (x *Transform_Request) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type Transform_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Record
	Record        []byte `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transform_Response) Reset() {
	*x = Transform_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transform_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transform_Response) ProtoMessage() {}

func (x *Transform_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transform_Response.ProtoReflect.Descriptor instead.
func (*Transform_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{11, 1}
}

func (x *Transform_Response) GetRecord() []byte {
	if x != nil {
		return x.Record
	}
	return nil
}

type TransformSchema_Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	Schema        []byte `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformSchema_Request) Reset() {
	*x = TransformSchema_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformSchema_Request) ProtoMessage() {}

func (x *TransformSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformSchema_Request.ProtoReflect.Descriptor instead.
func (*TransformSchema_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{12, 0}
}

func (x *TransformSchema_Request) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type TransformSchema_Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// marshalled arrow.Schema
	Schema        []byte `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransformSchema_Response) Reset() {
	*x = TransformSchema_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransformSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformSchema_Response) ProtoMessage() {}

func (x *TransformSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformSchema_Response.ProtoReflect.Descriptor instead.
func (*TransformSchema_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{12, 1}
}

func (x *TransformSchema_Response) GetSchema() []byte {
	if x != nil {
		return x.Schema
	}
	return nil
}

type Close_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close_Request) Reset() {
	*x = Close_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close_Request) ProtoMessage() {}

func (x *Close_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close_Request.ProtoReflect.Descriptor instead.
func (*Close_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{13, 0}
}

type Close_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Close_Response) Reset() {
	*x = Close_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Close_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Close_Response) ProtoMessage() {}

func (x *Close_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Close_Response.ProtoReflect.Descriptor instead.
func (*Close_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{13, 1}
}

type TestConnection_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          []byte                 `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"` // Internal plugin-specific spec
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnection_Request) Reset() {
	*x = TestConnection_Request{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnection_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnection_Request) ProtoMessage() {}

func (x *TestConnection_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnection_Request.ProtoReflect.Descriptor instead.
func (*TestConnection_Request) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{14, 0}
}

func (x *TestConnection_Request) GetSpec() []byte {
	if x != nil {
		return x.Spec
	}
	return nil
}

type TestConnection_Response struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Success            bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FailureCode        string                 `protobuf:"bytes,2,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	FailureDescription string                 `protobuf:"bytes,3,opt,name=failure_description,json=failureDescription,proto3" json:"failure_description,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TestConnection_Response) Reset() {
	*x = TestConnection_Response{}
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnection_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnection_Response) ProtoMessage() {}

func (x *TestConnection_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_pb_plugin_v3_plugin_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnection_Response.ProtoReflect.Descriptor instead.
func (*TestConnection_Response) Descriptor() ([]byte, []int) {
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP(), []int{14, 1}
}

func (x *TestConnection_Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestConnection_Response) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

func (x *TestConnection_Response) GetFailureDescription() string {
	if x != nil {
		return x.FailureDescription
	}
	return ""
}

var File_plugin_pb_plugin_v3_plugin_proto protoreflect.FileDescriptor

const file_plugin_pb_plugin_v3_plugin_proto_rawDesc = "" +
	"\n" +
	" plugin-pb/plugin/v3/plugin.proto\x12\x14cloudquery.plugin.v3\x1a\x1fgoogle/protobuf/timestamp.proto\"4\n" +
	"\aGetName\x1a\t\n" +
	"\aRequest\x1a\x1e\n" +
	"\bResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"=\n" +
	"\n" +
	"GetVersion\x1a\t\n" +
	"\aRequest\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\\\n" +
	"\rGetSpecSchema\x1a\t\n" +
	"\aRequest\x1a@\n" +
	"\bResponse\x12$\n" +
	"\vjson_schema\x18\x01 \x01(\tH\x00R\n" +
	"jsonSchema\x88\x01\x01B\x0e\n" +
	"\f_json_schema\"{\n" +
	"\x04Init\x1ag\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x12#\n" +
	"\rno_connection\x18\x02 \x01(\bR\fnoConnection\x12#\n" +
	"\rinvocation_id\x18\x03 \x01(\tR\finvocationId\x1a\n" +
	"\n" +
	"\bResponse\"\xa7\x01\n" +
	"\tGetTables\x1av\n" +
	"\aRequest\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\tR\x06tables\x12\x1f\n" +
	"\vskip_tables\x18\x02 \x03(\tR\n" +
	"skipTables\x122\n" +
	"\x15skip_dependent_tables\x18\x03 \x01(\bR\x13skipDependentTables\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\fR\x06tables\"\xa8\t\n" +
	"\x04Sync\x1a'\n" +
	"\rMessageInsert\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\x1a+\n" +
	"\x13MessageMigrateTable\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\x1a\xcc\x01\n" +
	"\x13MessageDeleteRecord\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12H\n" +
	"\fwhere_clause\x18\x02 \x03(\v2%.cloudquery.plugin.v3.PredicatesGroupR\vwhereClause\x12L\n" +
	"\x0ftable_relations\x18\x03 \x03(\v2#.cloudquery.plugin.v3.TableRelationR\x0etableRelations\x1aC\n" +
	"\fMessageError\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x1aO\n" +
	"\x0eBackendOptions\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12\x1e\n" +
	"\n" +
	"connection\x18\x02 \x01(\tR\n" +
	"connection\x1a\x99\x03\n" +
	"\aRequest\x12\x16\n" +
	"\x06tables\x18\x01 \x03(\tR\x06tables\x12\x1f\n" +
	"\vskip_tables\x18\x02 \x03(\tR\n" +
	"skipTables\x122\n" +
	"\x15skip_dependent_tables\x18\x03 \x01(\bR\x13skipDependentTables\x12.\n" +
	"\x13deterministic_cq_id\x18\x04 \x01(\bR\x11deterministicCqId\x12C\n" +
	"\abackend\x18\x05 \x01(\v2).cloudquery.plugin.v3.Sync.BackendOptionsR\abackend\x12C\n" +
	"\x05shard\x18\x06 \x01(\v2(.cloudquery.plugin.v3.Sync.Request.ShardH\x00R\x05shard\x88\x01\x01\x12,\n" +
	"\x11withErrorMessages\x18\a \x01(\bR\x11withErrorMessages\x1a/\n" +
	"\x05Shard\x12\x10\n" +
	"\x03num\x18\x01 \x01(\x05R\x03num\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05totalB\b\n" +
	"\x06_shard\x1a\xc8\x02\n" +
	"\bResponse\x12U\n" +
	"\rmigrate_table\x18\x01 \x01(\v2..cloudquery.plugin.v3.Sync.MessageMigrateTableH\x00R\fmigrateTable\x12B\n" +
	"\x06insert\x18\x02 \x01(\v2(.cloudquery.plugin.v3.Sync.MessageInsertH\x00R\x06insert\x12U\n" +
	"\rdelete_record\x18\x03 \x01(\v2..cloudquery.plugin.v3.Sync.MessageDeleteRecordH\x00R\fdeleteRecord\x12?\n" +
	"\x05error\x18\x04 \x01(\v2'.cloudquery.plugin.v3.Sync.MessageErrorH\x00R\x05errorB\t\n" +
	"\amessage\"K\n" +
	"\x04Read\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\"Q\n" +
	"\rTableRelation\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12!\n" +
	"\fparent_table\x18\x02 \x01(\tR\vparentTable\"\x95\x01\n" +
	"\tPredicate\x12D\n" +
	"\boperator\x18\x01 \x01(\x0e2(.cloudquery.plugin.v3.Predicate.OperatorR\boperator\x12\x16\n" +
	"\x06column\x18\x02 \x01(\tR\x06column\x12\x16\n" +
	"\x06record\x18\x03 \x01(\fR\x06record\"\x12\n" +
	"\bOperator\x12\x06\n" +
	"\x02EQ\x10\x00\"\xcc\x01\n" +
	"\x0fPredicatesGroup\x12W\n" +
	"\rgrouping_type\x18\x01 \x01(\x0e22.cloudquery.plugin.v3.PredicatesGroup.GroupingTypeR\fgroupingType\x12?\n" +
	"\n" +
	"predicates\x18\x02 \x03(\v2\x1f.cloudquery.plugin.v3.PredicateR\n" +
	"predicates\"\x1f\n" +
	"\fGroupingType\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01\"\xdd\x06\n" +
	"\x05Write\x1aP\n" +
	"\x13MessageMigrateTable\x12\x14\n" +
	"\x05table\x18\x01 \x01(\fR\x05table\x12#\n" +
	"\rmigrate_force\x18\x02 \x01(\bR\fmigrateForce\x1a'\n" +
	"\rMessageInsert\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\x1a\xa7\x01\n" +
	"\x12MessageDeleteStale\x12\x18\n" +
	"\x05table\x18\x01 \x01(\fB\x02\x18\x01R\x05table\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x127\n" +
	"\tsync_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsyncTime\x12\x1d\n" +
	"\n" +
	"table_name\x18\x04 \x01(\tR\ttableName\x1a\xcc\x01\n" +
	"\x13MessageDeleteRecord\x12\x1d\n" +
	"\n" +
	"table_name\x18\x01 \x01(\tR\ttableName\x12H\n" +
	"\fwhere_clause\x18\x02 \x03(\v2%.cloudquery.plugin.v3.PredicatesGroupR\vwhereClause\x12L\n" +
	"\x0ftable_relations\x18\x03 \x03(\v2#.cloudquery.plugin.v3.TableRelationR\x0etableRelations\x1a\xd3\x02\n" +
	"\aRequest\x12V\n" +
	"\rmigrate_table\x18\x01 \x01(\v2/.cloudquery.plugin.v3.Write.MessageMigrateTableH\x00R\fmigrateTable\x12C\n" +
	"\x06insert\x18\x02 \x01(\v2).cloudquery.plugin.v3.Write.MessageInsertH\x00R\x06insert\x12H\n" +
	"\x06delete\x18\x03 \x01(\v2..cloudquery.plugin.v3.Write.MessageDeleteStaleH\x00R\x06delete\x12V\n" +
	"\rdelete_record\x18\x04 \x01(\v2/.cloudquery.plugin.v3.Write.MessageDeleteRecordH\x00R\fdeleteRecordB\t\n" +
	"\amessage\x1a\n" +
	"\n" +
	"\bResponse\"R\n" +
	"\tTransform\x1a!\n" +
	"\aRequest\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06record\x18\x01 \x01(\fR\x06record\"X\n" +
	"\x0fTransformSchema\x1a!\n" +
	"\aRequest\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\fR\x06schema\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\fR\x06schema\"\x1e\n" +
	"\x05Close\x1a\t\n" +
	"\aRequest\x1a\n" +
	"\n" +
	"\bResponse\"\xa9\x01\n" +
	"\x0eTestConnection\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04spec\x18\x01 \x01(\fR\x04spec\x1ax\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ffailure_code\x18\x02 \x01(\tR\vfailureCode\x12/\n" +
	"\x13failure_description\x18\x03 \x01(\tR\x12failureDescription2\xf7\b\n" +
	"\x06Plugin\x12X\n" +
	"\aGetName\x12%.cloudquery.plugin.v3.GetName.Request\x1a&.cloudquery.plugin.v3.GetName.Response\x12a\n" +
	"\n" +
	"GetVersion\x12(.cloudquery.plugin.v3.GetVersion.Request\x1a).cloudquery.plugin.v3.GetVersion.Response\x12j\n" +
	"\rGetSpecSchema\x12+.cloudquery.plugin.v3.GetSpecSchema.Request\x1a,.cloudquery.plugin.v3.GetSpecSchema.Response\x12O\n" +
	"\x04Init\x12\".cloudquery.plugin.v3.Init.Request\x1a#.cloudquery.plugin.v3.Init.Response\x12^\n" +
	"\tGetTables\x12'.cloudquery.plugin.v3.GetTables.Request\x1a(.cloudquery.plugin.v3.GetTables.Response\x12Q\n" +
	"\x04Sync\x12\".cloudquery.plugin.v3.Sync.Request\x1a#.cloudquery.plugin.v3.Sync.Response0\x01\x12Q\n" +
	"\x04Read\x12\".cloudquery.plugin.v3.Read.Request\x1a#.cloudquery.plugin.v3.Read.Response0\x01\x12T\n" +
	"\x05Write\x12#.cloudquery.plugin.v3.Write.Request\x1a$.cloudquery.plugin.v3.Write.Response(\x01\x12b\n" +
	"\tTransform\x12'.cloudquery.plugin.v3.Transform.Request\x1a(.cloudquery.plugin.v3.Transform.Response(\x010\x01\x12p\n" +
	"\x0fTransformSchema\x12-.cloudquery.plugin.v3.TransformSchema.Request\x1a..cloudquery.plugin.v3.TransformSchema.Response\x12R\n" +
	"\x05Close\x12#.cloudquery.plugin.v3.Close.Request\x1a$.cloudquery.plugin.v3.Close.Response\x12m\n" +
	"\x0eTestConnection\x12,.cloudquery.plugin.v3.TestConnection.Request\x1a-.cloudquery.plugin.v3.TestConnection.ResponseBS\n" +
	"\x17io.cloudquery.plugin.v3P\x01Z6github.com/cloudquery/plugin-pb-go/pb/plugin/v3;pluginb\x06proto3"

var (
	file_plugin_pb_plugin_v3_plugin_proto_rawDescOnce sync.Once
	file_plugin_pb_plugin_v3_plugin_proto_rawDescData []byte
)

func file_plugin_pb_plugin_v3_plugin_proto_rawDescGZIP() []byte {
	file_plugin_pb_plugin_v3_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_pb_plugin_v3_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_pb_plugin_v3_plugin_proto_rawDesc), len(file_plugin_pb_plugin_v3_plugin_proto_rawDesc)))
	})
	return file_plugin_pb_plugin_v3_plugin_proto_rawDescData
}

var file_plugin_pb_plugin_v3_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plugin_pb_plugin_v3_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 49)
var file_plugin_pb_plugin_v3_plugin_proto_goTypes = []any{
	(Predicate_Operator)(0),           // 0: cloudquery.plugin.v3.Predicate.Operator
	(PredicatesGroup_GroupingType)(0), // 1: cloudquery.plugin.v3.PredicatesGroup.GroupingType
	(*GetName)(nil),                   // 2: cloudquery.plugin.v3.GetName
	(*GetVersion)(nil),                // 3: cloudquery.plugin.v3.GetVersion
	(*GetSpecSchema)(nil),             // 4: cloudquery.plugin.v3.GetSpecSchema
	(*Init)(nil),                      // 5: cloudquery.plugin.v3.Init
	(*GetTables)(nil),                 // 6: cloudquery.plugin.v3.GetTables
	(*Sync)(nil),                      // 7: cloudquery.plugin.v3.Sync
	(*Read)(nil),                      // 8: cloudquery.plugin.v3.Read
	(*TableRelation)(nil),             // 9: cloudquery.plugin.v3.TableRelation
	(*Predicate)(nil),                 // 10: cloudquery.plugin.v3.Predicate
	(*PredicatesGroup)(nil),           // 11: cloudquery.plugin.v3.PredicatesGroup
	(*Write)(nil),                     // 12: cloudquery.plugin.v3.Write
	(*Transform)(nil),                 // 13: cloudquery.plugin.v3.Transform
	(*TransformSchema)(nil),           // 14: cloudquery.plugin.v3.TransformSchema
	(*Close)(nil),                     // 15: cloudquery.plugin.v3.Close
	(*TestConnection)(nil),            // 16: cloudquery.plugin.v3.TestConnection
	(*GetName_Request)(nil),           // 17: cloudquery.plugin.v3.GetName.Request
	(*GetName_Response)(nil),          // 18: cloudquery.plugin.v3.GetName.Response
	(*GetVersion_Request)(nil),        // 19: cloudquery.plugin.v3.GetVersion.Request
	(*GetVersion_Response)(nil),       // 20: cloudquery.plugin.v3.GetVersion.Response
	(*GetSpecSchema_Request)(nil),     // 21: cloudquery.plugin.v3.GetSpecSchema.Request
	(*GetSpecSchema_Response)(nil),    // 22: cloudquery.plugin.v3.GetSpecSchema.Response
	(*Init_Request)(nil),              // 23: cloudquery.plugin.v3.Init.Request
	(*Init_Response)(nil),             // 24: cloudquery.plugin.v3.Init.Response
	(*GetTables_Request)(nil),         // 25: cloudquery.plugin.v3.GetTables.Request
	(*GetTables_Response)(nil),        // 26: cloudquery.plugin.v3.GetTables.Response
	(*Sync_MessageInsert)(nil),        // 27: cloudquery.plugin.v3.Sync.MessageInsert
	(*Sync_MessageMigrateTable)(nil),  // 28: cloudquery.plugin.v3.Sync.MessageMigrateTable
	(*Sync_MessageDeleteRecord)(nil),  // 29: cloudquery.plugin.v3.Sync.MessageDeleteRecord
	(*Sync_MessageError)(nil),         // 30: cloudquery.plugin.v3.Sync.MessageError
	(*Sync_BackendOptions)(nil),       // 31: cloudquery.plugin.v3.Sync.BackendOptions
	(*Sync_Request)(nil),              // 32: cloudquery.plugin.v3.Sync.Request
	(*Sync_Response)(nil),             // 33: cloudquery.plugin.v3.Sync.Response
	(*Sync_Request_Shard)(nil),        // 34: cloudquery.plugin.v3.Sync.Request.Shard
	(*Read_Request)(nil),              // 35: cloudquery.plugin.v3.Read.Request
	(*Read_Response)(nil),             // 36: cloudquery.plugin.v3.Read.Response
	(*Write_MessageMigrateTable)(nil), // 37: cloudquery.plugin.v3.Write.MessageMigrateTable
	(*Write_MessageInsert)(nil),       // 38: cloudquery.plugin.v3.Write.MessageInsert
	(*Write_MessageDeleteStale)(nil),  // 39: cloudquery.plugin.v3.Write.MessageDeleteStale
	(*Write_MessageDeleteRecord)(nil), // 40: cloudquery.plugin.v3.Write.MessageDeleteRecord
	(*Write_Request)(nil),             // 41: cloudquery.plugin.v3.Write.Request
	(*Write_Response)(nil),            // 42: cloudquery.plugin.v3.Write.Response
	(*Transform_Request)(nil),         // 43: cloudquery.plugin.v3.Transform.Request
	(*Transform_Response)(nil),        // 44: cloudquery.plugin.v3.Transform.Response
	(*TransformSchema_Request)(nil),   // 45: cloudquery.plugin.v3.TransformSchema.Request
	(*TransformSchema_Response)(nil),  // 46: cloudquery.plugin.v3.TransformSchema.Response
	(*Close_Request)(nil),             // 47: cloudquery.plugin.v3.Close.Request
	(*Close_Response)(nil),            // 48: cloudquery.plugin.v3.Close.Response
	(*TestConnection_Request)(nil),    // 49: cloudquery.plugin.v3.TestConnection.Request
	(*TestConnection_Response)(nil),   // 50: cloudquery.plugin.v3.TestConnection.Response
	(*timestamppb.Timestamp)(nil),     // 51: google.protobuf.Timestamp
}
var file_plugin_pb_plugin_v3_plugin_proto_depIdxs = []int32{
	0,  // 0: cloudquery.plugin.v3.Predicate.operator:type_name -> cloudquery.plugin.v3.Predicate.Operator
	1,  // 1: cloudquery.plugin.v3.PredicatesGroup.grouping_type:type_name -> cloudquery.plugin.v3.PredicatesGroup.GroupingType
	10, // 2: cloudquery.plugin.v3.PredicatesGroup.predicates:type_name -> cloudquery.plugin.v3.Predicate
	11, // 3: cloudquery.plugin.v3.Sync.MessageDeleteRecord.where_clause:type_name -> cloudquery.plugin.v3.PredicatesGroup
	9,  // 4: cloudquery.plugin.v3.Sync.MessageDeleteRecord.table_relations:type_name -> cloudquery.plugin.v3.TableRelation
	31, // 5: cloudquery.plugin.v3.Sync.Request.backend:type_name -> cloudquery.plugin.v3.Sync.BackendOptions
	34, // 6: cloudquery.plugin.v3.Sync.Request.shard:type_name -> cloudquery.plugin.v3.Sync.Request.Shard
	28, // 7: cloudquery.plugin.v3.Sync.Response.migrate_table:type_name -> cloudquery.plugin.v3.Sync.MessageMigrateTable
	27, // 8: cloudquery.plugin.v3.Sync.Response.insert:type_name -> cloudquery.plugin.v3.Sync.MessageInsert
	29, // 9: cloudquery.plugin.v3.Sync.Response.delete_record:type_name -> cloudquery.plugin.v3.Sync.MessageDeleteRecord
	30, // 10: cloudquery.plugin.v3.Sync.Response.error:type_name -> cloudquery.plugin.v3.Sync.MessageError
	51, // 11: cloudquery.plugin.v3.Write.MessageDeleteStale.sync_time:type_name -> google.protobuf.Timestamp
	11, // 12: cloudquery.plugin.v3.Write.MessageDeleteRecord.where_clause:type_name -> cloudquery.plugin.v3.PredicatesGroup
	9,  // 13: cloudquery.plugin.v3.Write.MessageDeleteRecord.table_relations:type_name -> cloudquery.plugin.v3.TableRelation
	37, // 14: cloudquery.plugin.v3.Write.Request.migrate_table:type_name -> cloudquery.plugin.v3.Write.MessageMigrateTable
	38, // 15: cloudquery.plugin.v3.Write.Request.insert:type_name -> cloudquery.plugin.v3.Write.MessageInsert
	39, // 16: cloudquery.plugin.v3.Write.Request.delete:type_name -> cloudquery.plugin.v3.Write.MessageDeleteStale
	40, // 17: cloudquery.plugin.v3.Write.Request.delete_record:type_name -> cloudquery.plugin.v3.Write.MessageDeleteRecord
	17, // 18: cloudquery.plugin.v3.Plugin.GetName:input_type -> cloudquery.plugin.v3.GetName.Request
	19, // 19: cloudquery.plugin.v3.Plugin.GetVersion:input_type -> cloudquery.plugin.v3.GetVersion.Request
	21, // 20: cloudquery.plugin.v3.Plugin.GetSpecSchema:input_type -> cloudquery.plugin.v3.GetSpecSchema.Request
	23, // 21: cloudquery.plugin.v3.Plugin.Init:input_type -> cloudquery.plugin.v3.Init.Request
	25, // 22: cloudquery.plugin.v3.Plugin.GetTables:input_type -> cloudquery.plugin.v3.GetTables.Request
	32, // 23: cloudquery.plugin.v3.Plugin.Sync:input_type -> cloudquery.plugin.v3.Sync.Request
	35, // 24: cloudquery.plugin.v3.Plugin.Read:input_type -> cloudquery.plugin.v3.Read.Request
	41, // 25: cloudquery.plugin.v3.Plugin.Write:input_type -> cloudquery.plugin.v3.Write.Request
	43, // 26: cloudquery.plugin.v3.Plugin.Transform:input_type -> cloudquery.plugin.v3.Transform.Request
	45, // 27: cloudquery.plugin.v3.Plugin.TransformSchema:input_type -> cloudquery.plugin.v3.TransformSchema.Request
	47, // 28: cloudquery.plugin.v3.Plugin.Close:input_type -> cloudquery.plugin.v3.Close.Request
	49, // 29: cloudquery.plugin.v3.Plugin.TestConnection:input_type -> cloudquery.plugin.v3.TestConnection.Request
	18, // 30: cloudquery.plugin.v3.Plugin.GetName:output_type -> cloudquery.plugin.v3.GetName.Response
	20, // 31: cloudquery.plugin.v3.Plugin.GetVersion:output_type -> cloudquery.plugin.v3.GetVersion.Response
	22, // 32: cloudquery.plugin.v3.Plugin.GetSpecSchema:output_type -> cloudquery.plugin.v3.GetSpecSchema.Response
	24, // 33: cloudquery.plugin.v3.Plugin.Init:output_type -> cloudquery.plugin.v3.Init.Response
	26, // 34: cloudquery.plugin.v3.Plugin.GetTables:output_type -> cloudquery.plugin.v3.GetTables.Response
	33, // 35: cloudquery.plugin.v3.Plugin.Sync:output_type -> cloudquery.plugin.v3.Sync.Response
	36, // 36: cloudquery.plugin.v3.Plugin.Read:output_type -> cloudquery.plugin.v3.Read.Response
	42, // 37: cloudquery.plugin.v3.Plugin.Write:output_type -> cloudquery.plugin.v3.Write.Response
	44, // 38: cloudquery.plugin.v3.Plugin.Transform:output_type -> cloudquery.plugin.v3.Transform.Response
	46, // 39: cloudquery.plugin.v3.Plugin.TransformSchema:output_type -> cloudquery.plugin.v3.TransformSchema.Response
	48, // 40: cloudquery.plugin.v3.Plugin.Close:output_type -> cloudquery.plugin.v3.Close.Response
	50, // 41: cloudquery.plugin.v3.Plugin.TestConnection:output_type -> cloudquery.plugin.v3.TestConnection.Response
	30, // [30:42] is the sub-list for method output_type
	18, // [18:30] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_plugin_pb_plugin_v3_plugin_proto_init() }
func file_plugin_pb_plugin_v3_plugin_proto_init() {
	if File_plugin_pb_plugin_v3_plugin_proto != nil {
		return
	}
	file_plugin_pb_plugin_v3_plugin_proto_msgTypes[20].OneofWrappers = []any{}
	file_plugin_pb_plugin_v3_plugin_proto_msgTypes[30].OneofWrappers = []any{}
	file_plugin_pb_plugin_v3_plugin_proto_msgTypes[31].OneofWrappers = []any{
		(*Sync_Response_MigrateTable)(nil),
		(*Sync_Response_Insert)(nil),
		(*Sync_Response_DeleteRecord)(nil),
		(*Sync_Response_Error)(nil),
	}
	file_plugin_pb_plugin_v3_plugin_proto_msgTypes[39].OneofWrappers = []any{
		(*Write_Request_MigrateTable)(nil),
		(*Write_Request_Insert)(nil),
		(*Write_Request_Delete)(nil),
		(*Write_Request_DeleteRecord)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_pb_plugin_v3_plugin_proto_rawDesc), len(file_plugin_pb_plugin_v3_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   49,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_pb_plugin_v3_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_pb_plugin_v3_plugin_proto_depIdxs,
		EnumInfos:         file_plugin_pb_plugin_v3_plugin_proto_enumTypes,
		MessageInfos:      file_plugin_pb_plugin_v3_plugin_proto_msgTypes,
	}.Build()
	File_plugin_pb_plugin_v3_plugin_proto = out.File
	file_plugin_pb_plugin_v3_plugin_proto_goTypes = nil
	file_plugin_pb_plugin_v3_plugin_proto_depIdxs = nil
}
